name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4

      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            scripts/**.py        

      - name: List all changed files
        if: needs.changes.outputs.packages != '[]'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
