name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ismodified: ${{ steps.listfiles.outputs.changed }}
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4

      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            scripts/**.py        

      - name: List all changed files
        id: listfiles
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        env:
          mod_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          concat_names="${mod_files// /;python }"
          echo "CMD [\"/bin/bash\", \"-c\", \"python $concat_names\"]" >> Dockerfile
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/metadata-action@v5
        with:
          images: dmeneguin/actions-test

      - name: echo meta outputs
        run: |
          echo "${{ steps.meta.outputs.tags }}"

      - name: Build and push
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dmeneguin/actions-test:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.ismodified}}
        run: echo "$OUTPUT1"
        
      - name: checkout external repo
        if: ${{ needs.build.outputs.ismodified }}
        uses: actions/checkout@v4
        with:
          repository: dmeneguin/actions-test-job-deployment
          ref: 'master'
          token: ${{ secrets.ACTIONS_PAT }}

      - name: kustomization
        if: ${{ needs.build.outputs.ismodified }}
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: dmeneguin/actions-test-job-deployment
          token: ${{ secrets.ACTIONS_PAT }}
          valueFile: 'kustomization.yaml'
          branch: dev
          targetBranch: master
          createPR: true
          description: Test GitHub Action
          message: 'Update All Images' 
          title: 'Version Updates '
          changes: |
            {
              "images[0].newTag": "${{ github.sha }}"
            }
