name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4

      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            scripts/**.py        

      - name: List all changed files
        env:
          mod_files: ${{ steps.changed-files.outputs.all_changed_files }}
        if: ${{ steps.changed-files.outputs.all_changed_files }} != '[]'
        run: |
          echo "$mod_files"
