name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4

      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            scripts/**.py        

      - name: List all changed files
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        env:
          mod_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          concat_names="${mod_files// /;python }"
          echo "CMD [\"/bin/bash\", \"-c\", \"python $concat_names\"]" >> Dockerfile
          cat Dockerfile

      - name: Login to Docker Hub
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/metadata-action@v5
        with:
          images: actions-test/docker-cmd-set

      - name: Build and push
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}