name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.build.outputs.ismodified }}
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4

      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            scripts/**.py        

      - name: List all changed files
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        env:
          mod_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          concat_names="${mod_files// /;python }"
          echo "CMD [\"/bin/bash\", \"-c\", \"python $concat_names\"]" >> Dockerfile
          echo "ismodified=true" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/metadata-action@v5
        with:
          images: dmeneguin/actions-test

      - name: echo meta outputs
        run: |
          echo "${{ steps.meta.outputs.tags }}"

      - name: Build and push
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dmeneguin/actions-test:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout external repo
        if: ${{ needs.build.outputs.ismodified }}
        uses: actions/checkout@v4
        with:
          repository: dmeneguin/actions-test-job-deployment
          ref: 'master'
          token: ${{ secrets.ACTIONS_PAT }}

      - name: kustomization
        if: ${{ needs.build.outputs.ismodified }}
        uses: williamhogman/kustomize-set-image-hook@v1.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          workingDirectory: .
          kustomizePath: .
          name: dmeneguin/actions-test
          newTag: ${{ github.sha }}
          newName: dmeneguin/actions-test

      # - name: Update values.yaml
      #   if: ${{ steps.changed-files.outputs.all_changed_files }}
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     valueFile: 'job.yaml'
      #     propertyPath: 'spec.template.containers[0].image'
      #     value: dmeneguin/actions-test:${{ github.sha }}
      #     branch: master/${{ github.sha }}
      #     targetBranch: master
      #     createPR: true
      #     message: 'Update Image Version to ${{ github.sha }}'
      #     token: ${{ secrets.ACTIONS_PAT }}
      #     repository: dmeneguin/actions-test-job-deployment
      
      # - name: setup git config and push
      #   if: ${{ steps.changed-files.outputs.all_changed_files }}
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"
      #     git push origin master
